### ISSUE TITLE
Propose an I/O scheduler concept

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/stdexec#839]
Perhaps @dietmarkuehl's sender-based networking paper [p2762](http://wg21.link/p2762) will be the ship vehicle for this one?

```[tasklist]
### Tasks
- [ ] async byte stream concepts (input/output) (plan to use a lot of ideas from Niall's networking/filesystem papers here)
- [ ] algorithms defined in terms of async byte stream concepts
- [ ] mechanism for obtaining an appropriate io-context type (e.g. do we have a set of predefined types, or do we have something that lets you request a context with particular features. e.g. you need file-io and timers, but not networking, or you need networking, but not files, etc.)
- [ ] concepts/cpos for obtaining a given i/o resource from a scheduler on an i/o context
- [ ] figure out interactions with i/o resources and @kirkshoop's async cleanup/async resource concept
- [ ] supporting types for networking (ip-addresses, network-masks, string parsing, etc.)
- [ ] network i/o resource/connection establishment facilities - do we want a socket-like thing? or just something that lets you ask to establish a new tcp/ssl/whatever connection and that hands you back a duplex async byte stream.
- [ ] name resolution (do we add facilities for doing this separately, or incorporate this into connection establishment for now?)
```
